### Get All USERS
### Heroku App: https://lcharleslaing-resume-api.herokuapp.com/
GET https://api-project-notes.vercel.app/api/users

###
GET https://api-project-notes.vercel.app/api/users/1

### Post New USERS
POST https://api-project-notes.vercel.app/api/users
Content-Type: application/json

{
  "email": "lcharleslaing@protonmail.com",
  "username": "leecharleslaing",
  "name": "leecharleslaing"
}

### Update One USERS
PATCH https://api-project-notes.vercel.app/api/users/1
Content-Type: application/json

{
  "email": "lcharleslaing@protonmail.com",
  "username": "leecharleslaing",
  "name": "leecharleslaing"
}


### Delete One USERS
DELETE https://api-project-notes.vercel.app/api/users/2

